apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-cce
  namespace: cce
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-cadavre-exquis-dispatcher
                port:
                  number: 80
            
